server {
    listen 8080;
    server_name _;

    charset utf-8;
    charset_types
        text/css
        text/plain
        text/html
        text/xml
        application/javascript
        text/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml;

    gzip on;
    
    location / {
        root /usr/share/nginx/html;
        index unresolvable-file-html.html;
        try_files $uri @index;
    }
    # This seperate location is so the no cache policy only applies to the index and nothing else.
    location @index {
        root /usr/share/nginx/html;
        add_header Cache-Control no-cache;
        expires 0;
        try_files /index.html =404;
    }
}
