import XCTest

nonisolated final class NavigationTests: UITestCase {
    @MainActor func testVisitedTabsKeepLoadedCards() {
        let app = launchApp(["--fail-repeated-library-loads"])
        XCTAssertTrue(app.buttons["media-movie-1"].firstMatch.waitForExistence(timeout: 10))
        XCUIRemote.shared.press(.up)
        for _ in 0..<3 {
            XCUIRemote.shared.press(.right)
            XCTAssertTrue(app.buttons["grid-series-1"].waitForExistence(timeout: 5))
            XCTAssertTrue(app.buttons["Series"].hasFocus)
            XCUIRemote.shared.press(.right)
            XCTAssertTrue(app.buttons["grid-movie-1"].waitForExistence(timeout: 5))
            XCTAssertTrue(app.buttons["Movies"].hasFocus)
            XCUIRemote.shared.press(.left)
            XCTAssertTrue(app.buttons["grid-series-1"].waitForExistence(timeout: 5))
            XCUIRemote.shared.press(.left)
            XCTAssertTrue(app.buttons["media-movie-1"].firstMatch.waitForExistence(timeout: 5))
            XCTAssertTrue(app.buttons["Home"].hasFocus)
            XCTAssertFalse(app.buttons["Retry"].exists)
        }
    }

    @MainActor func testMenuFocusSwitchesTabsAndConnectsToFirstPoster() {
        let app = launchApp(["--dense-catalog"])
        XCTAssertTrue(app.buttons["media-movie-1"].firstMatch.waitForExistence(timeout: 10))
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["Home"].hasFocus)
        XCUIRemote.shared.press(.right)
        XCTAssertTrue(app.buttons["grid-series-1"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["Series"].hasFocus)
        XCUIRemote.shared.press(.down)
        XCTAssertTrue(app.buttons["series-filters"].hasFocus)
        XCUIRemote.shared.press(.down)
        let series = app.buttons["grid-series-1"]
        let focused = XCTNSPredicateExpectation(predicate: NSPredicate(format: "hasFocus == true"), object: series)
        XCTAssertEqual(XCTWaiter.wait(for: [focused], timeout: 5), .completed)
        XCTAssertFalse(app.buttons["Refresh"].exists)
        attachScreenshot("Series with active menu and first poster focus")
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["series-filters"].hasFocus)
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["Series"].hasFocus)
        XCUIRemote.shared.press(.right)
        XCTAssertTrue(app.buttons["grid-movie-1"].waitForExistence(timeout: 5))
        XCUIRemote.shared.press(.down)
        XCTAssertTrue(app.buttons["movie-filters"].hasFocus)
        XCUIRemote.shared.press(.down)
        let movie = app.buttons["grid-movie-1"]
        let movieFocused = XCTNSPredicateExpectation(predicate: NSPredicate(format: "hasFocus == true"), object: movie)
        XCTAssertEqual(XCTWaiter.wait(for: [movieFocused], timeout: 5), .completed)
        XCUIRemote.shared.press(.right)
        XCUIRemote.shared.press(.right)
        XCUIRemote.shared.press(.right)
        XCTAssertTrue(app.buttons["grid-movie-4"].hasFocus)
        XCUIRemote.shared.press(.select)
        XCTAssertTrue(app.buttons["Play"].waitForExistence(timeout: 5))
        XCUIRemote.shared.press(.menu)
        XCTAssertTrue(app.buttons["grid-movie-4"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["grid-movie-4"].hasFocus)
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["movie-filters"].hasFocus)
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["Movies"].hasFocus)
        XCUIRemote.shared.press(.down)
        XCUIRemote.shared.press(.down)
        XCTAssertTrue(movie.hasFocus)
        XCUIRemote.shared.press(.down)
        XCTAssertFalse(app.buttons["Movies"].hasFocus)
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(movie.hasFocus)
        attachScreenshot("Dense movies grid with active tab")
        XCUIRemote.shared.press(.up)
        XCUIRemote.shared.press(.up)
        XCTAssertTrue(app.buttons["Movies"].hasFocus)
        select(app.buttons["movie-filters"], in: app)
        XCTAssertTrue(app.buttons["Apply Filters"].waitForExistence(timeout: 5))
    }
}
