version: '3.9'
services:
  elasticsearch:
    image: "elasticsearch:8.2.2"
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  redis:
    image: "redis:7"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb:10.10
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=seplis
    ports:
      - "3306:3306"
    volumes:
      - /var/seplisdb:/var/lib/mysql
  storitch:
    image: "thomaserlang/storitch:latest"
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - /var/storitch:/var/storitch
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile