version: '3.9'
services:
  elasticsearch:
    image: "elasticsearch:7.17.0"
    environment: 
      - discovery.type=single-node
    ports:
      - "9200:9200"
  redis:
    image: "redis:3-alpine"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  mariadb:
    image: "mariadb:latest"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=seplis
    ports:
      - "3306:3306"
  storitch:
    image: "thomaserlang/storitch:latest"
    ports:
      - "3000:80"
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile