name: build api

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: ./.github/workflows/_docker-build.yml
    secrets: inherit
    with:
      image_name: ${{ github.repository }}-api
      context: .
