name: build ui

on:
  push:
    tags:
      - "ui-v*"

jobs:
  build-and-push-image:
    uses: ./.github/workflows/_docker-build.yml
    secrets: inherit
    with:
      image_name: ${{ github.repository }}-ui
      context: ./seplis-ui
      dockerfile: seplis-ui/Dockerfile
      tag_prefix: ui-v
